sonar.projectKey=K0311_2025-ITCS383-Arai-Kor-Dai
sonar.organization=k0311-1

sonar.sources=.

sonar.c.file.suffixes=-
sonar.cpp.file.suffixes=-
sonar.objc.file.suffixes=-

# Exclude unnecessary files
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.html,**/*.css

# Ignore coverage if no tests yet
sonar.coverage.exclusions=**/*
