const db = require('../config/db');

/**
 * Report Model
 * Handles report-related database operations
 */
class Report {
  /**
   * Create a new report
   * @param {Object} reportData - Report data
   * @returns {Promise<Object>} Created report
   */
  static async create(reportData) {
    const { type, title, data, generated_by } = reportData;

    const query = `
      INSERT INTO reports (type, title, data, generated_by)
      VALUES ($1, $2, $3, $4)
      RETURNING *
    `;

    const values = [type, title, JSON.stringify(data), generated_by];
    const result = await db.query(query, values);
    return result.rows[0];
  }

  /**
   * Find report by ID
   * @param {number} id - Report ID
   * @returns {Promise<Object|null>} Report data or null
   */
  static async findById(id) {
    const query = 'SELECT * FROM reports WHERE id = $1';
    const result = await db.query(query, [id]);
    return result.rows[0] || null;
  }

  /**
   * Get all reports
   * @returns {Promise<Array>} Array of reports
   */
  static async findAll() {
    const query = 'SELECT * FROM reports ORDER BY created_at DESC';
    const result = await db.query(query);
    return result.rows;
  }

  /**
   * Get reports by type
   * @param {string} type - Report type
   * @returns {Promise<Array>} Array of reports
   */
  static async findByType(type) {
    const query = 'SELECT * FROM reports WHERE type = $1 ORDER BY created_at DESC';
    const result = await db.query(query, [type]);
    return result.rows;
  }

  /**
   * Get reports generated by a staff member
   * @param {number} staffId - Staff ID
   * @returns {Promise<Array>} Array of reports
   */
  static async findByStaffId(staffId) {
    const query = 'SELECT * FROM reports WHERE generated_by = $1 ORDER BY created_at DESC';
    const result = await db.query(query, [staffId]);
    return result.rows;
  }

  /**
   * Update report
   * @param {number} id - Report ID
   * @param {Object} updateData - Data to update
   * @returns {Promise<Object|null>} Updated report or null
   */
  static async update(id, updateData) {
    const fields = [];
    const values = [];
    let paramCount = 1;

    Object.keys(updateData).forEach(key => {
      if (updateData[key] !== undefined) {
        fields.push(`${key} = $${paramCount}`);
        values.push(key === 'data' ? JSON.stringify(updateData[key]) : updateData[key]);
        paramCount++;
      }
    });

    if (fields.length === 0) return null;

    const query = `
      UPDATE reports
      SET ${fields.join(', ')}
      WHERE id = $${paramCount}
      RETURNING *
    `;

    values.push(id);
    const result = await db.query(query, values);
    return result.rows[0] || null;
  }

  /**
   * Delete report
   * @param {number} id - Report ID
   * @returns {Promise<boolean>} Success status
   */
  static async delete(id) {
    const query = 'DELETE FROM reports WHERE id = $1';
    const result = await db.query(query, [id]);
    return result.rowCount > 0;
  }

  /**
   * Generate shipment statistics report
   * @param {string} startDate - Start date (YYYY-MM-DD)
   * @param {string} endDate - End date (YYYY-MM-DD)
   * @returns {Promise<Object>} Statistics data
   */
  static async generateShipmentStats(startDate, endDate) {
    const query = `
      SELECT
        COUNT(*) as total_shipments,
        COUNT(CASE WHEN status = 'delivered' THEN 1 END) as delivered_shipments,
        COUNT(CASE WHEN status = 'pending' THEN 1 END) as pending_shipments,
        COUNT(CASE WHEN status = 'shipped' THEN 1 END) as shipped_shipments,
        AVG(shipping_cost) as avg_cost,
        SUM(shipping_cost) as total_revenue
      FROM shipments
      WHERE DATE(created_at) BETWEEN $1 AND $2
    `;
    const result = await db.query(query, [startDate, endDate]);
    return result.rows[0];
  }

  /**
   * Generate payment statistics report
   * @param {string} startDate - Start date (YYYY-MM-DD)
   * @param {string} endDate - End date (YYYY-MM-DD)
   * @returns {Promise<Object>} Statistics data
   */
  static async generatePaymentStats(startDate, endDate) {
    const query = `
      SELECT
        COUNT(*) as total_payments,
        COUNT(CASE WHEN status = 'completed' THEN 1 END) as completed_payments,
        COUNT(CASE WHEN status = 'pending' THEN 1 END) as pending_payments,
        COUNT(CASE WHEN status = 'failed' THEN 1 END) as failed_payments,
        SUM(amount) as total_amount,
        AVG(amount) as avg_amount
      FROM payments
      WHERE DATE(created_at) BETWEEN $1 AND $2
    `;
    const result = await db.query(query, [startDate, endDate]);
    return result.rows[0];
  }

  /**
   * Generate customer statistics report
   * @param {string} startDate - Start date (YYYY-MM-DD)
   * @param {string} endDate - End date (YYYY-MM-DD)
   * @returns {Promise<Object>} Statistics data
   */
  static async generateCustomerStats(startDate, endDate) {
    const query = `
      SELECT
        COUNT(*) as total_customers,
        COUNT(CASE WHEN is_verified = true THEN 1 END) as verified_customers,
        COUNT(CASE WHEN is_verified = false THEN 1 END) as unverified_customers
      FROM customers
      WHERE DATE(created_at) BETWEEN $1 AND $2
    `;
    const result = await db.query(query, [startDate, endDate]);
    return result.rows[0];
  }
}

module.exports = Report;